"""add Department

Revision ID: 267e706f570c
Revises: 4cdd90054c6d
Create Date: 2024-06-27 13:37:16.550605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267e706f570c'
down_revision = '4cdd90054c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
